# This workflow will manually initiate the auto-versioning process
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Manually Update Pyscan Version for New Release

on:
  # Allow running manually from Actions tab
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    
    - name: git config
      run: |
        git config --global user.name "rsbrost"
        git config --global user.email "rsbrost@sandia.gov"
        git remote set-url origin https://x-access-token/:${{ secrets.REPO_TOKEN_SECRET }}@github.com/${{ github.repository }}

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        python -m pip install flake8
        python -m pip install pytest
        python -m pip install nbmake
        python -m pip install -e .

    - name: Lint with flake8
      run: |
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest

    - name: Test notebooks
      run: |
        pytest --nbmake "./demo_notebooks/" 

    # Autoversioning and updating changelog:
    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3.7.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: actions/create-release@v1
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.changelog.outputs.tag }}
        release_name: ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}