# This workflow will auto-release new versions when pull-requests are merged to main.
# Please note that there is no good way to make this work for pushing straight to main, so use pull-requests to auto-version pre release.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Release (On Merge to Main from Pull)

on:
  pull_request:
    branches: 
      - "main"
    types:
      - closed

permissions:
  contents: write

jobs:
  versioning_on_merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Branch to Modify
      run: git config push.default upstream

    # Autoversioning and updating changelog:
    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3.7.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        version-file: "VERSION.json"
        release-count: '30'
        skip-on-empty: 'false'

    - name: Create Release
      uses: actions/create-release@v1
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.changelog.outputs.tag }}
        release_name: ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}
