



# Autoversioning and updating changelog:
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5.2.1
        with:
          github-token: ${{ secrets.github_token }}
          version-file: "VERSION.json"
          release-count: '30'
