# This workflow will auto-version when changes are pushed directly to main.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Version New Release (On Direct Push)

on:
  pull_request:
    branches: 
      - "main"
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  versioning_on_push:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Get Version
      id: get_version
      run: |
        echo 'PACKAGE_JSON<<EOF' >> $GITHUB_ENV
        cat ./VERSION.json >> $GITHUB_ENV
        content=`cat VERSION.json`
        echo 'EOF' >> $GITHUB_ENV
    - run: |
        echo '${{ fromJson(env.PACKAGE_JSON).version }}'
        echo "::set-output name=versionJson::$content"
    - run: |
        echo "${{fromJson(steps.get_version.outputs.versionJson).version}}"

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{fromJSON(steps.get_version.outputs.versionJson).version}}
        release_name: ${{fromJSON(steps.get_version.outputs.versionJson).version}}
        body_path: CHANGELOG.md
