# This workflow will auto-version when changes are pushed directly to main.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Version New Release (On Direct Push)

on:
  pull_request:
    branches: 
      - "main"
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  versioning_on_push:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.base.ref }}

    - name: Get main version
      run: |
        echo 'MAIN_VERSION<<EOF' >> $GITHUB_ENV
        cat ./VERSION.json >> $GITHUB_ENV
        content=`cat VERSION.json`
        echo 'EOF' >> $GITHUB_ENV
    - run: |
        echo '${{ fromJson(env.MAIN_VERSION).version }}'
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Get HEAD version
      id: get_version
      run: |
        echo 'HEAD_VERSION<<EOF' >> $GITHUB_ENV
        cat ./VERSION.json >> $GITHUB_ENV
        content=`cat VERSION.json`
        echo 'EOF' >> $GITHUB_ENV
    - run: |
        echo '${{ fromJson(env.HEAD_VERSION).version }}'

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ fromJson(env.PACKAGE_JSON).version }}
        release_name: ${{ fromJson(env.PACKAGE_JSON).version }}
        body_path: CHANGELOG.md
