# This workflow will auto-version when changes are pushed directly to main.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Version New Release (On Direct Push)

on:
  workflow_dispatch:

permissions: write-all

jobs:
  versioning_on_push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: git config
      run: |
        git config --global user.name "rsbrost"
        git config --global user.email "rsbrost@sandia.gov"
        git remote set-url origin https://x-access-token/:${{ secrets.REPO_TOKEN_SECRET }}@github.com/${{ github.repository }}
    
    # Autoversioning and updating changelog:
    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3.7.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: actions/create-release@v1
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.changelog.outputs.tag }}
        release_name: ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}
